language: python
python:
 - "2.7"
 - "3.4"
 - "pypy-5.7.1"
 - "pypy3.5"
matrix:
  include:
  - os: osx
    language: generic
    env: USE_OPENMP=true
  - os: osx
    language: generic
    env: BREW_PYTHON3=old
  - os: osx
    language: generic
    env: PYPY_VERSION=6.0.0
  - os: osx
    language: generic
    env: USE_OPENMP=true BREW_PYTHON3=latest
  allow_failures:
  - env: USE_OPENMP=true BREW_PYTHON3=latest
  - python: pypy3.5
  fast_finish: true

# sudo is required to prevent xvfb crashes from container-based workers.
sudo: required
dist: trusty
cache: pip

addons:
  apt:
    packages:
      - libsdl2-dev

before_install:
- 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; fi'
- 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start; fi'
- 'if [[ "$BREW_PYTHON3" == "old" ]]; then HOMEBREW_NO_AUTO_UPDATE=1 brew install python3; fi'
- 'if [[ "$BREW_PYTHON3" == "latest" ]]; then brew upgrade python3; fi'
- 'if [[ -n "$BREW_PYTHON3" ]]; then python3 -m pip install virtualenv; fi'
- 'if [[ -n "$BREW_PYTHON3" ]]; then python3 -m virtualenv venv; fi'
- 'if [[ -n "$BREW_PYTHON3" ]]; then source venv/bin/activate; fi'
- 'if [[ "$TRAVIS_OS_NAME" == "osx" && "$USE_OPENMP" == "true" ]]; then source .travis/install_openmp.sh; fi'
- source .travis/install_python.sh
- 'wget https://bootstrap.pypa.io/get-pip.py'
- python get-pip.py
- pip install --upgrade setuptools
- pip install --pre --upgrade wheel
- pip install --requirement requirements.txt
install:
- if [[ -z "$TRAVIS_TAG" ]]; then export BUILD_FLAGS="-g"; fi
- python setup.py build $BUILD_FLAGS develop bdist_wheel --py-limited-api=cp34
- 'if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then python -m pip install git+git://github.com/HexDecimal/delocate.git@custom; fi'
- 'if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then delocate-wheel -v dist/*.whl; fi'
- 'if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then delocate-listdeps --all dist/*.whl; fi'
before_script:
 - pip install pytest pytest-cov
script:
- pytest -v
after_success:
- pip install codacy-coverage python-coveralls codecov
- codecov
- coveralls
- coverage xml
- if [[ -n "$CODACY_PROJECT_TOKEN" ]]; then python-codacy-coverage -r coverage.xml; fi
- if [[ -n "$TRAVIS_TAG" ]]; then pip install twine; fi
- if [[ -n "$TRAVIS_TAG" && "$TRAVIS_OS_NAME" == "osx" ]]; then twine upload --skip-existing dist/*; fi
