environment:
  TWINE_USERNAME:
    secure: 6EhNSnUl0yOO26EeQ5WG1pQx8v/vp99/u24NRpZvF0k=
  TWINE_PASSWORD:
    secure: PwPzzV8DPqw/+5M66FJQ5tbiF7rlOIK+bQIl8dFdF34=
  CODACY_PROJECT_TOKEN:
    secure: xprpiCGL823NKrs/K2Cps1UVBEmpezXReLxcfLyU1M43ZBBOK91xvjdIJamYKi8D
  DEPLOY_ONLY: false
  matrix:
  - PYTHON: C:\Python34-x64\python.exe
    platform: x64
  - PYTHON: C:\Python34\python.exe
    platform: Any CPU
  - PYTHON: C:\Python27\python.exe
    platform: Any CPU
  - PYPY: pypy2-v5.7.1-win32
    platform: Any CPU
  - PYTHON: C:\Python36-x64\python.exe
    platform: x64
  - PYTHON: C:\Python27-x64\python.exe
    platform: x64
    DEPLOY_ONLY: true
  - PYTHON: C:\Python35\python.exe
    platform: Any CPU
    DEPLOY_ONLY: true
  - PYTHON: C:\Python35-x64\python.exe
    platform: x64
    DEPLOY_ONLY: true
  - PYTHON: C:\Python36\python.exe
    platform: Any CPU
    DEPLOY_ONLY: true
  - PYPY: pypy2-v5.8.0-win32
    platform: Any CPU
    DEPLOY_ONLY: true
  - PYPY: pypy2-v5.9.0-win32
    platform: Any CPU
    DEPLOY_ONLY: true
  - PYPY: pypy2-v5.10.0-win32
    platform: Any CPU
    DEPLOY_ONLY: true
  - PYPY: pypy2-v6.0.0-win32
    platform: Any CPU
    DEPLOY_ONLY: true

matrix:
  allow_failures:
    - DEPLOY_ONLY: true
clone_depth: 20

cache:
  - '%localappdata%\pip\cache -> setup.py'

init:
- cmd: "if %APPVEYOR_REPO_TAG%==false if %DEPLOY_ONLY%==true exit /b 1"

install:
- cmd: "git submodule update --init --recursive"
- ps: ". .appveyor/install_python.ps1"
- cmd: "%ACTIVATE_VENV%"
- cmd: "python --version"
- cmd: "set PATH=%PATH%;C:\\MinGW\\bin"
- cmd: "pip install --upgrade setuptools"
- cmd: "if defined PYPY pip install git+https://bitbucket.org/pypy/numpy.git"
- cmd: "pip install --requirement requirements.txt"
- cmd: "python setup.py build sdist develop bdist_wheel"
build: off
before_test:
- cmd: "pip install pytest pytest-cov"
test_script:
- ps: "pytest -v"

on_success:
- pip install codacy-coverage python-coveralls
- coverage xml
- if defined CODACY_PROJECT_TOKEN python-codacy-coverage -r coverage.xml

deploy_script:
- "if defined APPVEYOR_REPO_TAG_NAME pip install twine"
- "if defined APPVEYOR_REPO_TAG_NAME twine upload --skip-existing dist/*"
